[keys.normal."#"]
"b" = "@:o .diag<ret>%d!(zig build run | complete).stderr<ret>gg/^[^ \t].+:\\d+:\\d+<ret><C-s>"
# build and open first diagnostic
"#" = "@:o .diag<ret>%d!(zig build run | complete).stderr<ret>gg/^[^ \t].+:\\d+:\\d+<ret><C-s>\"dy:o <C-r>d<ret>"
